In [1]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

In [2]:
title_basics = pd.read_csv(r"D:\Coding\Code\Python\ML\Data\IMDB\title.basics.tsv", sep="\t")
print("\nTitle.Akas")
title_basics

C:\Users\omarn\AppData\Local\Temp\ipykernel_18300\786484077.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  title_basics = pd.read_csv(r"D:\Coding\Code\Python\ML\Data\IMDB\title.basics.tsv", sep="\t")

Title.Akas

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
...,...,...,...,...,...,...,...,...,...
11319922,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,Drama
11319923,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,Drama
11319924,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,Drama
11319925,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
11319926,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [3]:
title_basics.replace("\\N", pd.NA , inplace=True)
title_basics.isna().sum()

tconst                   0
titleType                0
primaryTitle            19
originalTitle           19
isAdult                  1
startYear          1418389
endYear           11186328
runtimeMinutes     7737934
genres              501022
dtype: int64

In [4]:
title_basics_cleaned = title_basics.drop(columns=['isAdult', 'originalTitle', 'endYear','startYear','runtimeMinutes'])
title_basics_cleaned

,tconst,titleType,primaryTitle,genres
0,tt0000001,short,Carmencita,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,"Animation,Short"
2,tt0000003,short,Poor Pierrot,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Short
...,...,...,...,...
11319922,tt9916848,tvEpisode,Episode #3.17,Drama
11319923,tt9916850,tvEpisode,Episode #3.19,Drama
11319924,tt9916852,tvEpisode,Episode #3.20,Drama
11319925,tt9916856,short,The Wind,Short
11319926,tt9916880,tvEpisode,Horrid Henry Knows It All,"Adventure,Animation,Comedy"

In [5]:
title_basics_cleaned = title_basics_cleaned.dropna(subset=['genres','primaryTitle'])
title_basics_cleaned.isna().sum()

tconst          0
titleType       0
primaryTitle    0
genres          0
dtype: int64

In [ ]:
title_basics_cleaned['genres'] = title_basics_cleaned['genres'].apply(lambda x: x.split(',') if isinstance(x, str) else [])
title_basics_cleaned

C:\Users\omarn\AppData\Local\Temp\ipykernel_18300\1435371253.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  title_basics_cleaned['genres'] = title_basics_cleaned['genres'].apply(lambda x: x.split(',') if isinstance(x, str) else [])

,tconst,titleType,primaryTitle,genres
0,tt0000001,short,Carmencita,"[Documentary, Short]"
1,tt0000002,short,Le clown et ses chiens,"[Animation, Short]"
2,tt0000003,short,Poor Pierrot,"[Animation, Comedy, Romance]"
3,tt0000004,short,Un bon bock,"[Animation, Short]"
4,tt0000005,short,Blacksmith Scene,[Short]
...,...,...,...,...
11319922,tt9916848,tvEpisode,Episode #3.17,[Drama]
11319923,tt9916850,tvEpisode,Episode #3.19,[Drama]
11319924,tt9916852,tvEpisode,Episode #3.20,[Drama]
11319925,tt9916856,short,The Wind,[Short]
11319926,tt9916880,tvEpisode,Horrid Henry Knows It All,"[Adventure, Animation, Comedy]"

In [ ]:
title_basics_cleaned['genres'] = title_basics_cleaned['genres'].apply(lambda x: [genre.lower() for genre in x])
title_basics_cleaned

C:\Users\omarn\AppData\Local\Temp\ipykernel_18300\949480940.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  title_basics_cleaned['genres'] = title_basics_cleaned['genres'].apply(lambda x: [genre.lower() for genre in x])

,tconst,titleType,primaryTitle,genres
0,tt0000001,short,Carmencita,"[documentary, short]"
1,tt0000002,short,Le clown et ses chiens,"[animation, short]"
2,tt0000003,short,Poor Pierrot,"[animation, comedy, romance]"
3,tt0000004,short,Un bon bock,"[animation, short]"
4,tt0000005,short,Blacksmith Scene,[short]
...,...,...,...,...
11319922,tt9916848,tvEpisode,Episode #3.17,[drama]
11319923,tt9916850,tvEpisode,Episode #3.19,[drama]
11319924,tt9916852,tvEpisode,Episode #3.20,[drama]
11319925,tt9916856,short,The Wind,[short]
11319926,tt9916880,tvEpisode,Horrid Henry Knows It All,"[adventure, animation, comedy]"

In [8]:
title_basics_cleaned.to_csv(r"D:\Coding\Code\Python\ML\Data\IMDB\Cleaned Data\FinalGenreBasedRecomendation.csv")